services:

  proxy:
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf

  cms:
    image: localhost:5000/cms:v1
    build: 
      target: production
    env_file:
      - apps/cms/.env.production
    secrets: 
      - storage_account
      - storage_key
      - storage_secret
    environment:
      - STORAGE_ACCOUNT_FILE=/run/secrets/storage_account
      - STORAGE_KEY_FILE=/run/secrets/storage_key
      - STORAGE_SECRET_FILE=/run/secrets/storage_secret

secrets:
  cms_secret:
    external: true
  email_username:
    external: true
  email_password:
    external: true
  storage_account:
    external: true
  storage_key:
    external: true
  storage_secret:
    external: true
