services:

  web:
    build:
      context: .
      dockerfile: services/web/Dockerfile
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/web/src:/app/services/web/src
    depends_on:
      - cms

  cms:
    env_file:
      - services/cms/.env.development
