services:

  nginx:
    image: nginx:1.27
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - cms
    volumes:
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - production

  cms:
    image: ghcr.io/ecolier/ciroplaste-cms:1
    build:
      target: production
    secrets:
      - storage_account
      - storage_key
      - storage_secret
      - cms_secret
      - email_username
      - email_password
    environment:
      - STORAGE_ACCOUNT_FILE=/run/secrets/storage_account
      - STORAGE_KEY_FILE=/run/secrets/storage_key
      - STORAGE_SECRET_FILE=/run/secrets/storage_secret
      - SECRET_FILE=/run/secrets/cms_secret
      - EMAIL_USERNAME_FILE=/run/secrets/email_username
      - EMAIL_PASSWORD_FILE=/run/secrets/email_password
    networks:
      - production

secrets:
  cms_secret:
    external: true
  email_username:
    external: true
  email_password:
    external: true
  storage_account:
    external: true
  storage_key:
    external: true
  storage_secret:
    external: true

networks:
  production:
    driver: overlay
