services:

  content:
    build:
      context: .
      dockerfile: services/cms/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - services/cms/.env
    volumes:
      - media:/app/media
    networks:
      - node_network

  proxy:
    restart: unless-stopped
    image: nginx:1.27
    ports:
      - 80:80
    depends_on:
      - content
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    networks:
      - node_network

volumes:
  data:
  media:

networks:
  node_network:
