services:

  proxy:
    restart: unless-stopped
    image: nginx:1.27
    ports:
      - 80:80
    depends_on:
      - cms
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  cms:
    build: 
      target: production
    env_file:
      - services/cms/.env.production
