services:

  proxy:
    volumes:
      - ./development.conf:/etc/nginx/conf.d/default.conf
      - ./i18n:/home/www-data/i18n

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web:/app/apps/web
    depends_on:
      - cms

  cms:
    build: 
      target: development
    volumes:
      - ./apps/cms:/app/apps/cms
    env_file:
      - apps/cms/.env.development

