services:

  cms:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - content
    environment:
      - PAYLOAD_SECRET_FILE=/run/secrets/payload_secret
      - PAYLOAD_SMTP_USERNAME_FILE=/run/secrets/payload_smtp_username
      - PAYLOAD_SMTP_PASSWORD_FILE=/run/secrets/payload_smtp_password
    volumes:
      - media:/app/media
    secrets:
      - source: cms_secret
        target: payload_secret
      - source: smtp_username
        target: payload_smtp_username
      - source: smtp_password
        target: payload_smtp_password
  
  proxy:
    restart: unless-stopped
    image: nginx:1.27
    ports:
      - 80:80
    depends_on:
      - cms
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  content:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
  media:

secrets:
  cms_secret:
    environment: CMS_SECRET
  smtp_username:
    environment: CMS_SMTP_USERNAME
  smtp_password:
    environment: CMS_SMTP_PASSWORD
