services:

  proxy:
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf

  cms:
    image: localhost:5000/cms:v1
    build: 
      target: production
    env_file:
      - apps/cms/.env.production

secrets:
  cms_secret:
    external: true
  email_username:
    external: true
  email_password:
    external: true
  storage_account:
    external: true
  storage_key:
    external: true
  storage_secret:
    external: true
