services:

  cms:
    build:
      context: .
      dockerfile: services/cms/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - content
    environment:
      - PAYLOAD_SECRET_FILE=/run/secrets/payload_secret
    volumes:
      - media:/app/media
    secrets:
      - source: cms_secret
        target: payload_secret
        uid: '1001'
        gid: '1001'
        mode: 0440 

  content:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
  media:

secrets:
  cms_secret:
    environment: CMS_SECRET
