services:
  cms:
    build:
      target: development
    volumes:
      - ./apps/cms:/app/apps/cms
    networks:
      - development

  database:
    ports:
      - 27017:27017
    networks:
      - development

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ./apps/web:/app/apps/web
    networks:
      - development

networks:
  development:
    driver: bridge
