services:

  cms:
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - content
    volumes:
      - media:/app/media
    secrets:
      - cms_secret
      - email_username
      - email_password
    environment:
      - SECRET_FILE=/run/secrets/cms_secret
      - EMAIL_USERNAME_FILE=/run/secrets/email_username
      - EMAIL_PASSWORD_FILE=/run/secrets/email_password
  
  proxy:
    image: nginx:1.27
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - cms
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  content:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
  media:

networks:
  default:
    driver: bridge
