services:

  proxy:
    volumes:
      - ./local.conf:/etc/nginx/conf.d/default.conf

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    volumes:
      - ./apps/web:/app/apps/web
    depends_on:
      - cms

  cms:
    build: 
      target: development
    volumes:
      - ./apps/cms:/app/apps/cms
    env_file:
      - apps/cms/.env.development

