import type { Metadata } from "next";
import { Noto_Sans, Lora } from "next/font/google";
import localFont from "next/font/local";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages, setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import DrawerProvider from "@/components/drawer/drawer-provider";

import "./globals.css";
import { ThemeProvider } from "next-themes";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-sans",
});

const lora = Lora({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lora",
});

const ciroplasteSymbols = localFont({
  src: "./fonts/ciroplaste-symbols.woff2",
  variable: "--font-symbols",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  setRequestLocale(locale);
  const messages = await getMessages();
  return (
    <html
      lang={locale}
      className={`${notoSans.variable} ${lora.variable} ${ciroplasteSymbols.variable}`}
      suppressHydrationWarning
    >
      <body>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider attribute="class">
            <DrawerProvider>{children}</DrawerProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
